name: Publish and Release
on:
  push:
    branches:
      - master

permissions:
  contents: read # for checkout

jobs:
  # build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install
      - name: Build packages
        run: pnpm build

  # publish and release
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: pnpm publish --filter ./packages/*
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm --filter ./packages/* --workspace-concurrency=1 exec -- npx --no-install semantic-release -e semantic-release-monorepo
